package:
  name: smartctl-exporter
  version: 0.14.0
  epoch: 0
  description: Prometheus exporter for smartctl
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - smartmontools

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
  environment:
    CGO_ENABLED: "0"

vars:
  branch: unknown
  revision: unknown

pipeline:
  - uses: go/build
    with:
      packages: .
      output: smartctl_exporter
      ldflags: >-
        -s
        -X github.com/prometheus/common/version.Version=${{package.version}}
        -X github.com/prometheus/common/version.Revision=${{vars.revision}}
        -X github.com/prometheus/common/version.Branch=${{vars.branch}}
        -X github.com/prometheus/common/version.BuildUser=melange

test:
  pipeline:
    - runs: smartctl_exporter --version
